name: CI

on:
    push:
    pull_request:

jobs:
    php-cs-fixer:
        runs-on: ubuntu-latest
        timeout-minutes: 20
        strategy:
            matrix:
                php:
                    - '8.0'
            fail-fast: false
        env:
            PHP_CS_FIXER_FUTURE_MODE: '1'
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: curl, openssl, mbstring
                  ini-values: memory_limit=-1
                  tools: pecl, composer, php-cs-fixer
            - name: Run PHP-CS-Fixer fix
              run: php-cs-fixer fix --dry-run --diff --ansi

    phpstan:
        runs-on: ubuntu-latest
        timeout-minutes: 20
        strategy:
            matrix:
                php:
                    - '8.0'
            fail-fast: false
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: curl, openssl, mbstring
                  ini-values: memory_limit=-1
                  tools: composer
            - name: Update project dependencies
              run: composer update --no-interaction --no-progress --ansi
            - name: Run phpstan
              run: composer phpstan
